name: Release mosdns

on:
  push:
    tags:
      - 'v*'
  label:
    types:
      - created
jobs:

  build-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.23'
          check-latest: true
          cache: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Build
        run: python ./release.py
        env:
          CGO_ENABLED: '0'

      - name: Publish
        uses: softprops/action-gh-release@v2
        with:
          files: './release/mosdns*.zip'
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
